name: 'Build VPM index'
description: 'Build VPM index'


# Define your inputs here.
inputs:
  token:
  name:
  author:
  url:
  id:
  package:

outputs:
  index:
    description: Generated index.json Package Listing

runs:
  using: node20
  main: dist/index.js
