name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/vpm-index-action
        id: index
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: wholesome@ Package Listing
          author: wholesome@
          url: https://wholesomevr.github.io/vpm/index.json
          id: wholesome.listing
          package: wholesome.dependencies
      - run: echo '${{steps.index.outputs.index}}' >> _site/index.json
      - uses: actions/upload-pages-artifact@v3
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4