name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/vpm-index-action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: cat index.json